name: WMS Rollout PROD - Public Cloud
on:
  workflow_dispatch:
    inputs:
      Scheduled_Time:
        description: "In UTC timezone - (Format - dd/mm/yyyy HH:MM:SS). If not provided, request will be executed within next minute."
        required: false

jobs:
  dynamic-timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Set current timestamp in GMT
        id: get-timestamp
        run: echo "SCHEDULE_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV

      - name: Display Scheduled Time
        id: print-timestamp
        run: echo "Scheduled Time ${INPUT_SCHEDULED_TIME:-$SCHEDULE_TIMESTAMP}"
        env:
          INPUT_SCHEDULED_TIME: ${{ github.event.inputs.Scheduled_Time }}
          SCHEDULE_TIMESTAMP: ${{ env.SCHEDULE_TIMESTAMP }}
