name: Rollout Action
permissions:
  actions: write  
on:
  workflow_dispatch:

jobs:
  rollout:
    runs-on: ubuntu-latest
    steps:
      - name: Initial Preparation
        run: |
          echo "Starting rollout process..."
      
      - name: Wait for 5 minutes
        run: |
          echo "Waiting for 5 minutes before continuing..."
          sleep 300  # Waits for 300 seconds (5 minutes)
      
      - name: Continue with Rollout Tasks
        run: |
          echo "5 minutes passed. Proceeding with the rollout."
          # Add your actual rollout logic here
