name: Rollout Action
permissions:
  actions: write  
on:
  workflow_dispatch:
    inputs:
      server_name:
        description: 'Server name for rollout'
        required: true
      scheduled_time:
        description: 'Scheduled time for the rollout'
        required: true

jobs:
  perform_rollout:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          echo "Starting rollout for server: ${{ github.event.inputs.server_name }}"
          echo "Scheduled time: ${{ github.event.inputs.scheduled_time }}"
      - name: Initial Preparation
        run: |
          echo "Starting rollout process..."
      
      - name: Wait for 5 minutes
        run: |
          echo "Waiting for 5 minutes before continuing..."
          sleep 300  # Waits for 300 seconds (5 minutes)
      
      - name: Continue with Rollout Tasks
        run: |
          echo "5 minutes passed. Proceeding with the rollout."
          # Add your actual rollout logic here
